//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescaleAllImages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RescaleAllImagesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RescaleAllImagesStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RescaleAllImages.RescaleAllImagesStrings", typeof(RescaleAllImagesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path not selected ähnelt.
        /// </summary>
        internal static string path_notselected {
            get {
                return ResourceManager.GetString("path_notselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview for 
        ///{0}
        ///not available.
        ///
        /// ähnelt.
        /// </summary>
        internal static string preview_error {
            get {
                return ResourceManager.GetString("preview_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t create backup directory. ähnelt.
        /// </summary>
        internal static string process_backup_dir_error {
            get {
                return ResourceManager.GetString("process_backup_dir_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Couldn&apos;t move {0} to backup directory
        ///
        /// ähnelt.
        /// </summary>
        internal static string process_backup_move_original_error {
            get {
                return ResourceManager.GetString("process_backup_move_original_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///File successfully copied.
        ///
        /// ähnelt.
        /// </summary>
        internal static string process_backup_move_original_fallback_success {
            get {
                return ResourceManager.GetString("process_backup_move_original_fallback_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t copy file. Aborting. ähnelt.
        /// </summary>
        internal static string process_backup_move_original_fatal {
            get {
                return ResourceManager.GetString("process_backup_move_original_fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Couldn&apos;t compress {0}.
        ///
        /// ähnelt.
        /// </summary>
        internal static string process_compress_error {
            get {
                return ResourceManager.GetString("process_compress_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t copy file. Aborting. ähnelt.
        /// </summary>
        internal static string process_compress_error_fatal {
            get {
                return ResourceManager.GetString("process_compress_error_fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///File successfully copied.
        /// ähnelt.
        /// </summary>
        internal static string process_compress_fallback_success {
            get {
                return ResourceManager.GetString("process_compress_fallback_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t compress {0}. ähnelt.
        /// </summary>
        internal static string process_nobackup_error {
            get {
                return ResourceManager.GetString("process_nobackup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Can&apos;t delete original file {0}.
        ///
        /// ähnelt.
        /// </summary>
        internal static string process_nobackup_error_delete_source {
            get {
                return ResourceManager.GetString("process_nobackup_error_delete_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compressing folder
        ///{0}
        ///
        /// ähnelt.
        /// </summary>
        internal static string process_start {
            get {
                return ResourceManager.GetString("process_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Very rough quality ähnelt.
        /// </summary>
        internal static string quality_0 {
            get {
                return ResourceManager.GetString("quality_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rough quality ähnelt.
        /// </summary>
        internal static string quality_1 {
            get {
                return ResourceManager.GetString("quality_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal quality ähnelt.
        /// </summary>
        internal static string quality_2 {
            get {
                return ResourceManager.GetString("quality_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Above-average quality ähnelt.
        /// </summary>
        internal static string quality_3 {
            get {
                return ResourceManager.GetString("quality_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High quality ähnelt.
        /// </summary>
        internal static string quality_4 {
            get {
                return ResourceManager.GetString("quality_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Highest quality ähnelt.
        /// </summary>
        internal static string quality_5 {
            get {
                return ResourceManager.GetString("quality_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mini ähnelt.
        /// </summary>
        internal static string size_mini {
            get {
                return ResourceManager.GetString("size_mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poster ähnelt.
        /// </summary>
        internal static string size_poster {
            get {
                return ResourceManager.GetString("size_poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4K screen-sized ähnelt.
        /// </summary>
        internal static string size_quad {
            get {
                return ResourceManager.GetString("size_quad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screen-sized ähnelt.
        /// </summary>
        internal static string size_screen {
            get {
                return ResourceManager.GetString("size_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smartphone ähnelt.
        /// </summary>
        internal static string size_smartphone {
            get {
                return ResourceManager.GetString("size_smartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stamp ähnelt.
        /// </summary>
        internal static string size_stamp {
            get {
                return ResourceManager.GetString("size_stamp", resourceCulture);
            }
        }
    }
}
